// Unified type for OCR results from the backend
export interface EnhancedOCRResult {
  fullText: string;
  wordAnnotations: any[];
  spatialAnalysis: any;
}

// Core educational context structure generated by Gemini
export interface WhiteboardContext {
  content_analysis: {
    student_wrote: string;
    mathematical_elements: Array<{
      element: string;
      type: 'number' | 'operator' | 'variable' | 'equation';
      position: string;
      meaning: string;
    }>;
    problem_type: string;
    difficulty_assessment: string;
    student_progress_stage: string;
  };

  educational_context: {
    what_student_is_learning: string;
    common_challenges_here: string[];
    key_concepts_involved: string[];
    next_logical_steps: string[];
    potential_misconceptions: string[];
  };

  conversation_context: {
    whiteboard_description: string;
    things_to_reference: string[];
    questions_student_might_ask: string[];
    helpful_explanations_available: string[];
  };

  session_state: {
    problems_completed: number;
    current_focus_area: string;
    student_confidence_level: string;
    suggested_conversation_starters: string[];
  };
}

// Result wrapper for the context generation pipeline
export interface ContextResult {
  success: boolean;
  context?: WhiteboardContext;
  error?: string;
}

// Configuration for the VAPI service
export interface VAPIConfig {
  apiKey: string;
  assistantId: string;
}

// VAPI call status
export type VapiStatus = 'idle' | 'connecting' | 'connected' | 'error';

// Generic VAPI message type
export type VapiMessage = any; 